#!/bin/sh

set -e

LOOMWORKS_CONFIGURATION_FILE=/etc/loomworks/loomworks.conf
LOOMWORKS_GROUP="loomworks"
LOOMWORKS_DATA_DIR=/var/lib/loomworks
LOOMWORKS_LOG_DIR=/var/log/loomworks
LOOMWORKS_USER="loomworks"
GSFONTS_DIR=/usr/share/fonts/type1/gsfonts

case "${1}" in
    configure)
        if ! getent passwd | grep -q "^loomworks:"; then
            adduser --system --home $LOOMWORKS_DATA_DIR --quiet --group $LOOMWORKS_USER
            # Data dir
            chown $LOOMWORKS_USER:$LOOMWORKS_GROUP $LOOMWORKS_DATA_DIR
        fi
        # Register "$LOOMWORKS_USER" as a postgres user with "Create DB" role attribute
        su - postgres -c "createuser -d -R -S $LOOMWORKS_USER" 2> /dev/null || true
        # Configuration file
        chown $LOOMWORKS_USER:$LOOMWORKS_GROUP $LOOMWORKS_CONFIGURATION_FILE
        chmod 0640 $LOOMWORKS_CONFIGURATION_FILE
        # Log
        mkdir -p $LOOMWORKS_LOG_DIR
        chown $LOOMWORKS_USER:$LOOMWORKS_GROUP $LOOMWORKS_LOG_DIR
        chmod 0750 $LOOMWORKS_LOG_DIR
        	# work around https://bugs.debian.org/1059326

        if ! [ -e ${GSFONTS_DIR}/n021003l.pfb ] ; then
            if ! [ -d ${GSFONTS_DIR} ] ; then
                mkdir ${GSFONTS_DIR}
                touch ${GSFONTS_DIR}/.created-by-loomworks-package
            fi
            ln -s /usr/share/fonts/X11/Type1/C059-Roman.pfb ${GSFONTS_DIR}/n021003l.pfb
        fi
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
